using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Normal.Realtime;
using Normal.Realtime.Serialization;

[RealtimeModel]
public partial class BoostDataModel
{
    [RealtimeProperty(1, true, true)]
    private bool _boosting;
}

/* ----- Begin Normal Autogenerated Code ----- */
public partial class BoostDataModel : RealtimeModel {
    public bool boosting {
        get {
            return _boostingProperty.value;
        }
        set {
            if (_boostingProperty.value == value) return;
            _boostingProperty.value = value;
            InvalidateReliableLength();
            FireBoostingDidChange(value);
        }
    }
    
    public delegate void PropertyChangedHandler<in T>(BoostDataModel model, T value);
    public event PropertyChangedHandler<bool> boostingDidChange;
    
    public enum PropertyID : uint {
        Boosting = 1,
    }
    
    #region Properties
    
    private ReliableProperty<bool> _boostingProperty;
    
    #endregion
    
    public BoostDataModel() : base(null) {
        _boostingProperty = new ReliableProperty<bool>(1, _boosting);
    }
    
    protected override void OnParentReplaced(RealtimeModel previousParent, RealtimeModel currentParent) {
        _boostingProperty.UnsubscribeCallback();
    }
    
    private void FireBoostingDidChange(bool value) {
        try {
            boostingDidChange?.Invoke(this, value);
        } catch (System.Exception exception) {
            UnityEngine.Debug.LogException(exception);
        }
    }
    
    protected override int WriteLength(StreamContext context) {
        var length = 0;
        length += _boostingProperty.WriteLength(context);
        return length;
    }
    
    protected override void Write(WriteStream stream, StreamContext context) {
        var writes = false;
        writes |= _boostingProperty.Write(stream, context);
        if (writes) InvalidateContextLength(context);
    }
    
    protected override void Read(ReadStream stream, StreamContext context) {
        var anyPropertiesChanged = false;
        while (stream.ReadNextPropertyID(out uint propertyID)) {
            var changed = false;
            switch (propertyID) {
                case (uint) PropertyID.Boosting: {
                    changed = _boostingProperty.Read(stream, context);
                    if (changed) FireBoostingDidChange(boosting);
                    break;
                }
                default: {
                    stream.SkipProperty();
                    break;
                }
            }
            anyPropertiesChanged |= changed;
        }
        if (anyPropertiesChanged) {
            UpdateBackingFields();
        }
    }
    
    private void UpdateBackingFields() {
        _boosting = boosting;
    }
    
}
/* ----- End Normal Autogenerated Code ----- */
